DOcker image

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1208,34 +1208,24 @@ jobs:
           done
 
 
-      - name: Commit generated ArgoCD Application manifests
+      - name: Commit and push generated ArgoCD Application manifests
         env:
           GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git add k8s/argocd/applications/
-          if ! git diff --staged --quiet; then
-            git commit -m "Generate/Update ArgoCD Application manifests for ${{ github.sha }}"
-          else
-            echo "No changes to ArgoCD Application manifests to commit."
-            exit 0
-          fi
-      - name: Pull latest changes before pushing
-        run: |
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git config --global user.name 'github-actions[bot]'
-          git pull --rebase origin feature/improvements
-      - name: Push changes to feature/improvements branch
-        run: |
-          git push origin HEAD:feature/improvements
-          fi
+
+          git pull --rebase --autostash origin feature/improvements || {
+            echo "⚠️ Git pull failed, possibly due to merge conflict or empty pull."
+          }
+
+          git push origin feature/improvements
 
   lint-and-deploy-helm:
     if: ${{ github.event.inputs.destroy_infra != 'true' }}
     env:
       IS_DESTROY: ${{ github.event.inputs.destroy == 'true' }}
-    needs: [docker, deploy-argocd] # Changed from generate-argo-apps to deploy-argocd
+    needs: [docker, deploy-argocd, genereate-argo-apps] # Changed from generate-argo-apps to deploy-argocd
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
