TF destroy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -510,15 +510,25 @@ jobs:
           AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
           helm repo add eks https://aws.github.io/eks-charts
           helm repo update
-          helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
-            -n kube-system \
-            --set clusterName=${{ env.APP_NAME }} \
-            --set serviceAccount.create=false \
-            --set serviceAccount.name=aws-load-balancer-controller \
-            --set region=${{ env.AWS_REGION }} \
-            --set vpcId=${{ env.VPC_ID }} \
-            --wait # Wait for the ALB Controller deployment to be ready
-          kubectl rollout status deployment aws-load-balancer-controller -n kube-system --timeout=5m # Explicitly check rollout status
+
+          for i in {1..3}; do
+            echo "Attempt $i: Installing AWS Load Balancer Controller..."
+            helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
+              -n kube-system \
+              --set clusterName=${{ env.APP_NAME }} \
+              --set serviceAccount.create=true \
+              --set serviceAccount.name=aws-load-balancer-controller \
+              --set rbac.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${{ env.ALB_CONTROLLER_ROLE_ARN }} \
+              --set region=${{ env.AWS_REGION }} \
+              --set vpcId=${{ env.VPC_ID }} \
+              --timeout 20m \
+              --wait && break || {
+                echo "Attempt $i failed. Retrying in 10 seconds..."
+                sleep 10
+              }
+          done
+
+          kubectl rollout status deployment aws-load-balancer-controller -n kube-system --timeout=5m
             
       - name: Get ACM certificate ARN from Terraform
         id: get-cert-arn
